name: deoldify
channels:
- fastai
- conda-forge
- defaults
dependencies:
- pip
- fastai=2.8.3
- mkl=2024.0
- python=3.12
- pytorch::pytorch=2.8.0
- pytorch::torchvision
- pytorch::torchaudio
- tensorboardX
- jupyterlab
- pillow>=11.3.0
- ipywidgets
- ffmpeg
- pip:
  - ffmpeg-python
  - opencv-python>=4.12.0.88
  - wandb
  - yt-dlp
